Clear pbench remotes before configuring
openshift-scale/workloads pull request #122
Opened 2020-03-24 20:04 UTC by chaitanyaenr

This commit fixes the issue where there might be stale remotes
left from the previous benchmark runs which might no longer exist
because of operations like scale down. pbench-clear-tools is run to
clear them before configuring the remotes for each benchmark run.

2020-03-24 20:05 UTC, chaitanyaenr commented
Fixes #121

2020-03-27 20:26 UTC, rsevilla87 commented
I ran into this issue from a different path. In my case I reinstalled the tools and they were scheduled on different nodes.

2020-03-27 20:46 UTC, rsevilla87 requested changes
I've tried to execute the workaround manually. And I found out that the  `pbench-clear-tools ` command returns !=0 when it's not able to clean tools from a remote node, so this change will make the workload to hang in those cases  since the bash interpreter is configured with the exit option on the line 8.

```
[root@ovn ~]# echo "master" > /var/lib/pbench-agent/tools-default/remote@1.2.3.4
[root@ovn ~]# pbench-clear-tools
running . /opt/pbench-agent/profile; pbench-clear-tools --group default  on 1.2.3.4
ssh: connect to host 1.2.3.4 port 22: Connection timed out
Removing the remote remote@1.2.3.4
[root@ovn ~]# echo $?
1
```

A workaround might be to disable exit during this command execution with `set +e`  and re-enable it later, or we might also move forward the  `set -eo pipefail` statement.

2020-03-31 21:51 UTC, chaitanyaenr commented
Nice catch @rsevilla87, modified the command to exit 0 explicitly to avoid hitting the issue when the remote host no longer exists for it clear tools. PTAL.

2020-03-31 22:26 UTC, rsevilla87 commented
@chaitanyaenr the proposed workaround will also break as the `pipefail` bash option is set.
According to the official bash documentation:

_If set, the return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully_


Considering that we'll need to disable pipefail before the command `pbench-clear-tools` i.e.
```bash
$ set +eo pipefail
$ pbench-clear-tools
$ set -eo pipefail
```
Note that exit 0 is no longer required as we've also disabled bash exit option.

Hope that helps ;)

2020-04-03 14:07 UTC, chaitanyaenr commented
@rsevilla87 it definitely helps, will make the change. Thanks.

2020-04-29 01:22 UTC, chaitanyaenr commented
@rsevilla87 Made the suggested changes. PTAL.

2020-04-29 10:56 UTC, rsevilla87 commented
lgtm @chaitanyaenr

2020-04-29 10:57 UTC, rsevilla87 approved these changes

2020-04-29 13:33 UTC, aakarshg approved these changes
LGTM

2020-04-29 13:33 UTC, merged